from typing import Protocol, List, Dict, Any
class VectorStore(Protocol):
    def upsert(self, embeddings: Any, metas: List[Dict]): ...
    def search(self, query_emb: Any, top_k: int = 5) -> List[Dict]: ...
class MetadataStore(Protocol):
    def upsert(self, records: List[Dict]): ...
    def query(self, **filters) -> List[Dict]: ...
